version: '2'
services:
  tinkuy-nodebb:
    restart: always
    build: ./nodebb
    links:
      - tinkuy-redis
    volumes:
      - ./config/nodebb.config.json:/nodebb/config.json:ro
      - tinkuy-nodebb:/nodebb/public/uploads
  tinkuy-redis:
    restart: always
    image: redis:3
    volumes: 
      - tinkuy-redis:/data
  couchdb:
    restart: always
    image: couchdb:1
    volumes: 
      - couchdb:/usr/local/var/lib/couchdb
  caddy:
    restart: always
    build: ./caddy
    links:
      - tinkuy-nodebb
      - couchdb
    volumes: 
      - ./config/Caddyfile:/caddy/Caddyfile:ro
      - caddy:/root/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
volumes:
  caddy: {"driver": "local"}
  couchdb: {"driver": "local"}
  tinkuy-nodebb: {"driver": "local"}
  tinkuy-redis: {"driver": "local"}
