version: '2'
services:
  tinkuy-nodebb:
    restart: always
    build: ./nodebb
    links:
      - tinkuy-redis
    volumes:
      - ./tinkuy-nodebb.config.json:/nodebb/config.json:ro
      - tinkuy-nodebb:/nodebb/public/uploads
  tinkuy-redis:
    restart: always
    image: redis:3
    volumes: 
      - tinkuy-redis:/data
  couchdb:
    restart: always
    image: couchdb:1
    volumes: 
      - couchdb:/usr/local/var/lib/couchdb
  owncloud:
    # PW3
    restart: always
    image: owncloud:9
    volumes: 
      - owncloud:/var/www/html
  piwik-mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $PW2
    volumes:
      - piwik-mysql:/var/lib/mysql
  piwik:
    restart: always
    image: marvambass/piwik
    environment:
      PIWIK_MYSQL_USER: root
      PIWIK_MYSQL_PASSWORD: $PW2
      PIWIK_MYSQL_HOST: piwik-mysql
      PIWIK_ADMIN_PASSWORD: $PW2
      SITE_URL: https://solsort.com
  bornekor-mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $PW1
    volumes:
      - bornekor-mysql2:/var/lib/mysql
  bornekor:
    restart: always
    image: wordpress
    links:
      - bornekor-mysql
    environment:
      WORDPRESS_DB_HOST: bornekor-mysql
      WORDPRESS_DB_PASSWORD: $PW1
    volumes:
      - bornekor-wordpress2:/var/www/html
  alive-mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $PW1
    volumes:
      - alive-mysql:/var/lib/mysql
  alive:
    restart: always
    image: wordpress
    links:
      - alive-mysql
    environment:
      WORDPRESS_DB_HOST: alive-mysql
      WORDPRESS_DB_PASSWORD: $PW1
    volumes:
      - alive-wordpress:/var/www/html
  rasmuserik-mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $PW1
    volumes:
      - rasmuserik-mysql:/var/lib/mysql
  rasmuserik:
    restart: always
    image: wordpress
    links:
      - rasmuserik-mysql
    environment:
      WORDPRESS_DB_HOST: rasmuserik-mysql
      WORDPRESS_DB_PASSWORD: $PW1
    volumes:
      - rasmuserik-wordpress:/var/www/html
  annevoel-mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $PW1
    volumes:
      - annevoel-mysql:/var/lib/mysql
  annevoel:
    restart: always
    image: wordpress
    links:
      - annevoel-mysql
    environment:
      WORDPRESS_DB_HOST: annevoel-mysql
      WORDPRESS_DB_PASSWORD: $PW1
    volumes:
      - annevoel-wordpress:/var/www/html
  mysql-admin:
    restart: always
    image: clue/adminer
    links:
      - rasmuserik-mysql
  caddy:
    restart: always
    build: ./caddy
    links:
      - tinkuy-nodebb
      - couchdb
      - rasmuserik
      - annevoel 
      - alive
      - mysql-admin
      - piwik
    volumes: 
      - ./Caddyfile:/caddy/Caddyfile:ro
      - caddy:/root/.caddy
      - ../apps:/apps
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
volumes:
  caddy: {"driver": "local"}
  couchdb: {"driver": "local"}
  tinkuy-nodebb: {"driver": "local"}
  tinkuy-redis: {"driver": "local"}
  bornekor-wordpress2: {"driver": "local"}
  bornekor-mysql2: {"driver": "local"}
  alive-wordpress: {"driver": "local"}
  alive-mysql: {"driver": "local"}
  rasmuserik-wordpress: {"driver": "local"}
  rasmuserik-mysql: {"driver": "local"}
  annevoel-wordpress: {"driver": "local"}
  annevoel-mysql: {"driver": "local"}
  piwik-mysql: {"driver": "local"}
  owncloud: {"driver": "local"}
